<a href="https://colab.research.google.com/github/bipinthecoder/learn-tensorflow/blob/main/TensorFlow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.tensorflow.org/guide/basics


In [2]:
import tensorflow as tf
import numpy as np


Creating a Tensor


In [ ]:
x = tf.constant([[1., 2., 3.],[4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)


tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


**A "scalar" or "rank-0" tensor contains a single value, and no "axes".**

In [3]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)


tf.Tensor(4, shape=(), dtype=int32)


**A "vector" or "rank-1" tensor is like a list of values. A vector has one axis:**



In [4]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


**A "matrix" or "rank-2" tensor has two axes:**

In [5]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)


tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


**convert a tensor to a NumPy array**

 - either using np.array() 
 - or the tensor.numpy method

In [8]:
np.array(rank_2_tensor)


array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [9]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

**Normal tf.Tensorobjects are immutable. To store model weights (or other mutable state) in TensorFlow use a tf.Variable.**

In [ ]:
var = tf.Variable([0.0, 0.0, 0.0])
var.assign([1, 2, 3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

We can mention datatype explicitly in the Variable function:

In [16]:
string_var = tf.Variable("This is a string", dtype=tf.string)
number_var = tf.Variable(165, dtype=tf.int16)
floating_var = tf.Variable(165.32, dtype=tf.float64)

In [17]:
print(number_var)

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=165>


Performing Operations:

In [ ]:
var.assign([1, 2, 3])
var.assign_add([1, 1, 1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

Rank/Degree of Tensor: It describes the number of dimesnions. If dimesnions are 0, it is scalar otherwise it is a vector

In [ ]:
rank1_tensor = tf.Variable([["Bipin","Babu"]], tf.string)
rank2_tensor = tf.Variable([["One", "Two","Three"], ["Four","Five","Six"]], tf.string)

In [ ]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
tf.rank(string_var)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
rank2_tensor.shape

TensorShape([2, 3])

Reshaping Tensors:

When reshaping, the number of elements remain the same, just the dimensions change. also when the shape figures are multiplied it gives the total number of elements.

In [ ]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3, -1])

-1 here aks the tensor to complete the dimesnion in that place automatically for us

In [ ]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


Types of Tensors
- Variable - Mutable
- Constant - Immutable
- Placeholder - Immutable
- SparseTensor - Immutable

Evaluate a Tensor:
Sometimes we need to evaluate a tensor, which means by finding its value. Since Tensors are partially complete computations, we have to run a session to evaluate the tensor

In [ ]:
# with tf.Session() as sess
#   tensor_name.eval()

In [3]:
test_variable = tf.Variable(2)
test_variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>